<Project>
	<ItemGroup>
		<PackageVersion Include="CardsView.Maui" Version="1.1.2" />
		<PackageVersion Include="CommunityToolkit.Maui" Version="14.1.0" />
		<PackageVersion Include="CommunityToolkit.Maui.Markup" Version="7.0.1" />
		<PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="10.0.5" />
		<PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.5" />
		<PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.41" />
		<PackageVersion Include="Reactor.Maui" Version="4.0.17" />
		<PackageVersion Include="Reactor.Maui.HotReload" Version="4.0.17" />
	</ItemGroup>
</Project>
