//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerApp.App.Forms.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BeerApp.App.Forms.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        internal static string TermsAndConditionsBody {
            get {
                return ResourceManager.GetString("TermsAndConditionsBody", resourceCulture);
            }
        }
        
        internal static string TaxIncluded {
            get {
                return ResourceManager.GetString("TaxIncluded", resourceCulture);
            }
        }
        
        internal static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        internal static string ButtonAccept {
            get {
                return ResourceManager.GetString("ButtonAccept", resourceCulture);
            }
        }
        
        internal static string Yen {
            get {
                return ResourceManager.GetString("Yen", resourceCulture);
            }
        }
        
        internal static string YenBeforeNumber {
            get {
                return ResourceManager.GetString("YenBeforeNumber", resourceCulture);
            }
        }
        
        internal static string NetworkDisconnected {
            get {
                return ResourceManager.GetString("NetworkDisconnected", resourceCulture);
            }
        }
        
        internal static string AccountEmailAddress {
            get {
                return ResourceManager.GetString("AccountEmailAddress", resourceCulture);
            }
        }
        
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        internal static string AccountShippingAddress {
            get {
                return ResourceManager.GetString("AccountShippingAddress", resourceCulture);
            }
        }
        
        internal static string AccountPhoneNumber {
            get {
                return ResourceManager.GetString("AccountPhoneNumber", resourceCulture);
            }
        }
        
        internal static string AccountPhoneNumberTip {
            get {
                return ResourceManager.GetString("AccountPhoneNumberTip", resourceCulture);
            }
        }
        
        internal static string AccountProblemAccessForbiddenTitle {
            get {
                return ResourceManager.GetString("AccountProblemAccessForbiddenTitle", resourceCulture);
            }
        }
        
        internal static string AccountProblemAccessForbidden {
            get {
                return ResourceManager.GetString("AccountProblemAccessForbidden", resourceCulture);
            }
        }
        
        internal static string AccountProblemContactInformationInvalid {
            get {
                return ResourceManager.GetString("AccountProblemContactInformationInvalid", resourceCulture);
            }
        }
        
        internal static string AccountProblemCreditCardInvalid {
            get {
                return ResourceManager.GetString("AccountProblemCreditCardInvalid", resourceCulture);
            }
        }
        
        internal static string AccountProblemEmailAlreadyExists {
            get {
                return ResourceManager.GetString("AccountProblemEmailAlreadyExists", resourceCulture);
            }
        }
        
        internal static string AccountProblemShippingAddressInvalid {
            get {
                return ResourceManager.GetString("AccountProblemShippingAddressInvalid", resourceCulture);
            }
        }
        
        internal static string AccountProblemUnknownError {
            get {
                return ResourceManager.GetString("AccountProblemUnknownError", resourceCulture);
            }
        }
        
        internal static string AddressPostalCode {
            get {
                return ResourceManager.GetString("AddressPostalCode", resourceCulture);
            }
        }
        
        internal static string AddressPrefecture {
            get {
                return ResourceManager.GetString("AddressPrefecture", resourceCulture);
            }
        }
        
        internal static string AddressLocal {
            get {
                return ResourceManager.GetString("AddressLocal", resourceCulture);
            }
        }
        
        internal static string CreditCardSameAsShipping {
            get {
                return ResourceManager.GetString("CreditCardSameAsShipping", resourceCulture);
            }
        }
        
        internal static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }
        
        internal static string CreateAccountButtonCreate {
            get {
                return ResourceManager.GetString("CreateAccountButtonCreate", resourceCulture);
            }
        }
        
        internal static string CreateAccountAgreeToTerms {
            get {
                return ResourceManager.GetString("CreateAccountAgreeToTerms", resourceCulture);
            }
        }
        
        internal static string CreateAccountBirthdate {
            get {
                return ResourceManager.GetString("CreateAccountBirthdate", resourceCulture);
            }
        }
        
        internal static string CreateAccountBirthdateTip {
            get {
                return ResourceManager.GetString("CreateAccountBirthdateTip", resourceCulture);
            }
        }
        
        internal static string EditAccountTitle {
            get {
                return ResourceManager.GetString("EditAccountTitle", resourceCulture);
            }
        }
        
        internal static string EditContactInfoLink {
            get {
                return ResourceManager.GetString("EditContactInfoLink", resourceCulture);
            }
        }
        
        internal static string EditShippingAddressLink {
            get {
                return ResourceManager.GetString("EditShippingAddressLink", resourceCulture);
            }
        }
        
        internal static string ChangePaymentMethodLink {
            get {
                return ResourceManager.GetString("ChangePaymentMethodLink", resourceCulture);
            }
        }
        
        internal static string EditContactInformationTitle {
            get {
                return ResourceManager.GetString("EditContactInformationTitle", resourceCulture);
            }
        }
        
        internal static string EditShippingAddressTitle {
            get {
                return ResourceManager.GetString("EditShippingAddressTitle", resourceCulture);
            }
        }
        
        internal static string EditPaymentMethodTitle {
            get {
                return ResourceManager.GetString("EditPaymentMethodTitle", resourceCulture);
            }
        }
        
        internal static string EditAccountButtonSave {
            get {
                return ResourceManager.GetString("EditAccountButtonSave", resourceCulture);
            }
        }
        
        internal static string CreditCardNotStoredOnServer {
            get {
                return ResourceManager.GetString("CreditCardNotStoredOnServer", resourceCulture);
            }
        }
        
        internal static string CreditCardAllowedCards {
            get {
                return ResourceManager.GetString("CreditCardAllowedCards", resourceCulture);
            }
        }
        
        internal static string CreditCardNameOnCard {
            get {
                return ResourceManager.GetString("CreditCardNameOnCard", resourceCulture);
            }
        }
        
        internal static string CreditCardCardNumber {
            get {
                return ResourceManager.GetString("CreditCardCardNumber", resourceCulture);
            }
        }
        
        internal static string CreditCardExpiration {
            get {
                return ResourceManager.GetString("CreditCardExpiration", resourceCulture);
            }
        }
        
        internal static string CreditCardExpirationMonth {
            get {
                return ResourceManager.GetString("CreditCardExpirationMonth", resourceCulture);
            }
        }
        
        internal static string CreditCardExpirationYear {
            get {
                return ResourceManager.GetString("CreditCardExpirationYear", resourceCulture);
            }
        }
        
        internal static string CreditCardVerificationCode {
            get {
                return ResourceManager.GetString("CreditCardVerificationCode", resourceCulture);
            }
        }
        
        internal static string CreditCardAddress {
            get {
                return ResourceManager.GetString("CreditCardAddress", resourceCulture);
            }
        }
        
        internal static string PaymentMethodProblemTitle {
            get {
                return ResourceManager.GetString("PaymentMethodProblemTitle", resourceCulture);
            }
        }
        
        internal static string PaymentMethodProblemBody {
            get {
                return ResourceManager.GetString("PaymentMethodProblemBody", resourceCulture);
            }
        }
        
        internal static string PaymentMethodProblemNewCreditCard {
            get {
                return ResourceManager.GetString("PaymentMethodProblemNewCreditCard", resourceCulture);
            }
        }
        
        internal static string PaymentMethodProblemNewCreditCardLater {
            get {
                return ResourceManager.GetString("PaymentMethodProblemNewCreditCardLater", resourceCulture);
            }
        }
        
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        internal static string LoginButtonLogin {
            get {
                return ResourceManager.GetString("LoginButtonLogin", resourceCulture);
            }
        }
        
        internal static string LoginAccountUnknown {
            get {
                return ResourceManager.GetString("LoginAccountUnknown", resourceCulture);
            }
        }
        
        internal static string LoginProblem {
            get {
                return ResourceManager.GetString("LoginProblem", resourceCulture);
            }
        }
        
        internal static string WaitVerificationTitle {
            get {
                return ResourceManager.GetString("WaitVerificationTitle", resourceCulture);
            }
        }
        
        internal static string WaitVerificationExplanation1 {
            get {
                return ResourceManager.GetString("WaitVerificationExplanation1", resourceCulture);
            }
        }
        
        internal static string WaitVerificationExplanation2 {
            get {
                return ResourceManager.GetString("WaitVerificationExplanation2", resourceCulture);
            }
        }
        
        internal static string WaitVerificationMergeBoxTitle {
            get {
                return ResourceManager.GetString("WaitVerificationMergeBoxTitle", resourceCulture);
            }
        }
        
        internal static string WaitVerificationMergeBoxDescription {
            get {
                return ResourceManager.GetString("WaitVerificationMergeBoxDescription", resourceCulture);
            }
        }
        
        internal static string NotificationAlertCancel {
            get {
                return ResourceManager.GetString("NotificationAlertCancel", resourceCulture);
            }
        }
        
        internal static string NotificationAlertRefreshOffers {
            get {
                return ResourceManager.GetString("NotificationAlertRefreshOffers", resourceCulture);
            }
        }
        
        internal static string NotificationAlertShowOffers {
            get {
                return ResourceManager.GetString("NotificationAlertShowOffers", resourceCulture);
            }
        }
        
        internal static string SummaryTitle {
            get {
                return ResourceManager.GetString("SummaryTitle", resourceCulture);
            }
        }
        
        internal static string SummaryNotLoggedIn {
            get {
                return ResourceManager.GetString("SummaryNotLoggedIn", resourceCulture);
            }
        }
        
        internal static string SummaryCosts {
            get {
                return ResourceManager.GetString("SummaryCosts", resourceCulture);
            }
        }
        
        internal static string SummaryCostsBeers {
            get {
                return ResourceManager.GetString("SummaryCostsBeers", resourceCulture);
            }
        }
        
        internal static string SummaryCostsShipping {
            get {
                return ResourceManager.GetString("SummaryCostsShipping", resourceCulture);
            }
        }
        
        internal static string SummaryCostsTotal {
            get {
                return ResourceManager.GetString("SummaryCostsTotal", resourceCulture);
            }
        }
        
        internal static string SummaryCostsShippingTip {
            get {
                return ResourceManager.GetString("SummaryCostsShippingTip", resourceCulture);
            }
        }
        
        internal static string SummaryEndDate {
            get {
                return ResourceManager.GetString("SummaryEndDate", resourceCulture);
            }
        }
        
        internal static string SummaryShipDate {
            get {
                return ResourceManager.GetString("SummaryShipDate", resourceCulture);
            }
        }
        
        internal static string SummarySelectedBeers {
            get {
                return ResourceManager.GetString("SummarySelectedBeers", resourceCulture);
            }
        }
        
        internal static string SummaryLinkShowDetails {
            get {
                return ResourceManager.GetString("SummaryLinkShowDetails", resourceCulture);
            }
        }
        
        internal static string SummaryUniqueBeers {
            get {
                return ResourceManager.GetString("SummaryUniqueBeers", resourceCulture);
            }
        }
        
        internal static string SummaryTotalBeers {
            get {
                return ResourceManager.GetString("SummaryTotalBeers", resourceCulture);
            }
        }
        
        internal static string OrderRecentlyClosedTitle {
            get {
                return ResourceManager.GetString("OrderRecentlyClosedTitle", resourceCulture);
            }
        }
        
        internal static string OrderRecentlyClosedDescription {
            get {
                return ResourceManager.GetString("OrderRecentlyClosedDescription", resourceCulture);
            }
        }
        
        internal static string OrderEndingSoonTitle {
            get {
                return ResourceManager.GetString("OrderEndingSoonTitle", resourceCulture);
            }
        }
        
        internal static string OrderEndingSoonDescription {
            get {
                return ResourceManager.GetString("OrderEndingSoonDescription", resourceCulture);
            }
        }
        
        internal static string OrderEntriesTitle {
            get {
                return ResourceManager.GetString("OrderEntriesTitle", resourceCulture);
            }
        }
        
        internal static string OrderHistoryTitle {
            get {
                return ResourceManager.GetString("OrderHistoryTitle", resourceCulture);
            }
        }
        
        internal static string PaymentMethodHeader {
            get {
                return ResourceManager.GetString("PaymentMethodHeader", resourceCulture);
            }
        }
        
        internal static string PaymentMethodCreditCard {
            get {
                return ResourceManager.GetString("PaymentMethodCreditCard", resourceCulture);
            }
        }
        
        internal static string PaymentMethodCOD {
            get {
                return ResourceManager.GetString("PaymentMethodCOD", resourceCulture);
            }
        }
        
        internal static string PaymentMethodStatusCardDeclined {
            get {
                return ResourceManager.GetString("PaymentMethodStatusCardDeclined", resourceCulture);
            }
        }
        
        internal static string PaymentMethodStatusExpiredCard {
            get {
                return ResourceManager.GetString("PaymentMethodStatusExpiredCard", resourceCulture);
            }
        }
        
        internal static string PaymentMethodStatusIncorrectCvc {
            get {
                return ResourceManager.GetString("PaymentMethodStatusIncorrectCvc", resourceCulture);
            }
        }
        
        internal static string PaymentMethodStatusIncorrectNumber {
            get {
                return ResourceManager.GetString("PaymentMethodStatusIncorrectNumber", resourceCulture);
            }
        }
        
        internal static string PaymentMethodStatusIncorrectZip {
            get {
                return ResourceManager.GetString("PaymentMethodStatusIncorrectZip", resourceCulture);
            }
        }
        
        internal static string PaymentMethodStatusInvalidCvc {
            get {
                return ResourceManager.GetString("PaymentMethodStatusInvalidCvc", resourceCulture);
            }
        }
        
        internal static string PaymentMethodStatusInvalidExpiryMonth {
            get {
                return ResourceManager.GetString("PaymentMethodStatusInvalidExpiryMonth", resourceCulture);
            }
        }
        
        internal static string PaymentMethodStatusInvalidExpiryYear {
            get {
                return ResourceManager.GetString("PaymentMethodStatusInvalidExpiryYear", resourceCulture);
            }
        }
        
        internal static string PaymentMethodStatusInvalidNumber {
            get {
                return ResourceManager.GetString("PaymentMethodStatusInvalidNumber", resourceCulture);
            }
        }
        
        internal static string PaymentMethodStatusUnknown {
            get {
                return ResourceManager.GetString("PaymentMethodStatusUnknown", resourceCulture);
            }
        }
        
        internal static string BeerDetailsTitle {
            get {
                return ResourceManager.GetString("BeerDetailsTitle", resourceCulture);
            }
        }
        
        internal static string BeerDetailsABV {
            get {
                return ResourceManager.GetString("BeerDetailsABV", resourceCulture);
            }
        }
        
        internal static string BeerDetailsABVUnknown {
            get {
                return ResourceManager.GetString("BeerDetailsABVUnknown", resourceCulture);
            }
        }
        
        internal static string BeerDetailsIBU {
            get {
                return ResourceManager.GetString("BeerDetailsIBU", resourceCulture);
            }
        }
        
        internal static string BeerDetailsIBUUnknown {
            get {
                return ResourceManager.GetString("BeerDetailsIBUUnknown", resourceCulture);
            }
        }
        
        internal static string BeerDetailsContainer {
            get {
                return ResourceManager.GetString("BeerDetailsContainer", resourceCulture);
            }
        }
        
        internal static string BeerDetailsSize {
            get {
                return ResourceManager.GetString("BeerDetailsSize", resourceCulture);
            }
        }
        
        internal static string BeerDetailsSeperator {
            get {
                return ResourceManager.GetString("BeerDetailsSeperator", resourceCulture);
            }
        }
        
        internal static string OffersTitle {
            get {
                return ResourceManager.GetString("OffersTitle", resourceCulture);
            }
        }
        
        internal static string OffersNoCurrent1 {
            get {
                return ResourceManager.GetString("OffersNoCurrent1", resourceCulture);
            }
        }
        
        internal static string OffersNoCurrent2 {
            get {
                return ResourceManager.GetString("OffersNoCurrent2", resourceCulture);
            }
        }
        
        internal static string OfferNotLoggedInTitle {
            get {
                return ResourceManager.GetString("OfferNotLoggedInTitle", resourceCulture);
            }
        }
        
        internal static string OfferNotLoggedInDescription {
            get {
                return ResourceManager.GetString("OfferNotLoggedInDescription", resourceCulture);
            }
        }
        
        internal static string OfferNotLoggedInLoginNow {
            get {
                return ResourceManager.GetString("OfferNotLoggedInLoginNow", resourceCulture);
            }
        }
        
        internal static string OfferNotLoggedInLoginLater {
            get {
                return ResourceManager.GetString("OfferNotLoggedInLoginLater", resourceCulture);
            }
        }
        
        internal static string OfferPrice {
            get {
                return ResourceManager.GetString("OfferPrice", resourceCulture);
            }
        }
        
        internal static string OfferTotal {
            get {
                return ResourceManager.GetString("OfferTotal", resourceCulture);
            }
        }
        
        internal static string OfferQuantity {
            get {
                return ResourceManager.GetString("OfferQuantity", resourceCulture);
            }
        }
        
        internal static string OfferConfirmAdd {
            get {
                return ResourceManager.GetString("OfferConfirmAdd", resourceCulture);
            }
        }
        
        internal static string OfferConfirmUpdate {
            get {
                return ResourceManager.GetString("OfferConfirmUpdate", resourceCulture);
            }
        }
        
        internal static string OfferNone {
            get {
                return ResourceManager.GetString("OfferNone", resourceCulture);
            }
        }
        
        internal static string OfferQuantityIncrement {
            get {
                return ResourceManager.GetString("OfferQuantityIncrement", resourceCulture);
            }
        }
        
        internal static string OfferQuantityDecrement {
            get {
                return ResourceManager.GetString("OfferQuantityDecrement", resourceCulture);
            }
        }
        
        internal static string OfferQuantityLimits {
            get {
                return ResourceManager.GetString("OfferQuantityLimits", resourceCulture);
            }
        }
        
        internal static string OfferInsufficientInventoryTitle {
            get {
                return ResourceManager.GetString("OfferInsufficientInventoryTitle", resourceCulture);
            }
        }
        
        internal static string OfferInsufficientInventory {
            get {
                return ResourceManager.GetString("OfferInsufficientInventory", resourceCulture);
            }
        }
        
        internal static string OfferNoInventoryTitle {
            get {
                return ResourceManager.GetString("OfferNoInventoryTitle", resourceCulture);
            }
        }
        
        internal static string OfferNoInventory {
            get {
                return ResourceManager.GetString("OfferNoInventory", resourceCulture);
            }
        }
        
        internal static string OfferProblemAddingTitle {
            get {
                return ResourceManager.GetString("OfferProblemAddingTitle", resourceCulture);
            }
        }
        
        internal static string OfferProblemAdding {
            get {
                return ResourceManager.GetString("OfferProblemAdding", resourceCulture);
            }
        }
        
        internal static string UntappdRating {
            get {
                return ResourceManager.GetString("UntappdRating", resourceCulture);
            }
        }
        
        internal static string UntappdPersonalRating {
            get {
                return ResourceManager.GetString("UntappdPersonalRating", resourceCulture);
            }
        }
        
        internal static string OfferAlmostGone {
            get {
                return ResourceManager.GetString("OfferAlmostGone", resourceCulture);
            }
        }
        
        internal static string OfferExclusive {
            get {
                return ResourceManager.GetString("OfferExclusive", resourceCulture);
            }
        }
        
        internal static string OfferRare {
            get {
                return ResourceManager.GetString("OfferRare", resourceCulture);
            }
        }
        
        internal static string OfferSale {
            get {
                return ResourceManager.GetString("OfferSale", resourceCulture);
            }
        }
        
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        internal static string SettingsLanguageSystem {
            get {
                return ResourceManager.GetString("SettingsLanguageSystem", resourceCulture);
            }
        }
        
        internal static string SettingsLanguageEnglish {
            get {
                return ResourceManager.GetString("SettingsLanguageEnglish", resourceCulture);
            }
        }
        
        internal static string SettingsLanguageJapanese {
            get {
                return ResourceManager.GetString("SettingsLanguageJapanese", resourceCulture);
            }
        }
        
        internal static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        internal static string SettingsThemeSystem {
            get {
                return ResourceManager.GetString("SettingsThemeSystem", resourceCulture);
            }
        }
        
        internal static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }
        
        internal static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }
        
        internal static string SettingsUntappd {
            get {
                return ResourceManager.GetString("SettingsUntappd", resourceCulture);
            }
        }
        
        internal static string SettingsUntappdAbout1 {
            get {
                return ResourceManager.GetString("SettingsUntappdAbout1", resourceCulture);
            }
        }
        
        internal static string SettingsUntappdAbout2 {
            get {
                return ResourceManager.GetString("SettingsUntappdAbout2", resourceCulture);
            }
        }
        
        internal static string SettingsUntappdGlobalRating {
            get {
                return ResourceManager.GetString("SettingsUntappdGlobalRating", resourceCulture);
            }
        }
        
        internal static string SettingsUntappdPersonalRating {
            get {
                return ResourceManager.GetString("SettingsUntappdPersonalRating", resourceCulture);
            }
        }
        
        internal static string SettingsUntappdLogin {
            get {
                return ResourceManager.GetString("SettingsUntappdLogin", resourceCulture);
            }
        }
        
        internal static string SettingsUntappdLoginTip {
            get {
                return ResourceManager.GetString("SettingsUntappdLoginTip", resourceCulture);
            }
        }
        
        internal static string UntappdLoginTitle {
            get {
                return ResourceManager.GetString("UntappdLoginTitle", resourceCulture);
            }
        }
        
        internal static string UntappdLoginStatusEstablishingConnection {
            get {
                return ResourceManager.GetString("UntappdLoginStatusEstablishingConnection", resourceCulture);
            }
        }
        
        internal static string UntappdLoginStatusLogin {
            get {
                return ResourceManager.GetString("UntappdLoginStatusLogin", resourceCulture);
            }
        }
        
        internal static string UntappdLoginStatusVerifications {
            get {
                return ResourceManager.GetString("UntappdLoginStatusVerifications", resourceCulture);
            }
        }
        
        internal static string UntappdLoginStatusDone {
            get {
                return ResourceManager.GetString("UntappdLoginStatusDone", resourceCulture);
            }
        }
        
        internal static string HowItWorksTitle {
            get {
                return ResourceManager.GetString("HowItWorksTitle", resourceCulture);
            }
        }
        
        internal static string HowItWorksGetStarted {
            get {
                return ResourceManager.GetString("HowItWorksGetStarted", resourceCulture);
            }
        }
        
        internal static string HowItWorksContinue {
            get {
                return ResourceManager.GetString("HowItWorksContinue", resourceCulture);
            }
        }
        
        internal static string HowItWorksShowMeTheBeers {
            get {
                return ResourceManager.GetString("HowItWorksShowMeTheBeers", resourceCulture);
            }
        }
        
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        internal static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }
        
        internal static string ContactUsSubject {
            get {
                return ResourceManager.GetString("ContactUsSubject", resourceCulture);
            }
        }
        
        internal static string ContactUsMessage {
            get {
                return ResourceManager.GetString("ContactUsMessage", resourceCulture);
            }
        }
        
        internal static string ContactUsButtonSend {
            get {
                return ResourceManager.GetString("ContactUsButtonSend", resourceCulture);
            }
        }
        
        internal static string OldVersionExplanation {
            get {
                return ResourceManager.GetString("OldVersionExplanation", resourceCulture);
            }
        }
        
        internal static string OldVersionUpdateNow {
            get {
                return ResourceManager.GetString("OldVersionUpdateNow", resourceCulture);
            }
        }
    }
}
