//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beerbox.App.Resources.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beerbox.App.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compelling craft beer delivered cold to your door!.
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to email address.
        /// </summary>
        internal static string AccountEmailAddress {
            get {
                return ResourceManager.GetString("AccountEmailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TEL.
        /// </summary>
        internal static string AccountPhoneNumber {
            get {
                return ResourceManager.GetString("AccountPhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Needed for delivery courier..
        /// </summary>
        internal static string AccountPhoneNumberTip {
            get {
                return ResourceManager.GetString("AccountPhoneNumberTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Looks like there was a problem updating your account. Please login again..
        /// </summary>
        internal static string AccountProblemAccessForbidden {
            get {
                return ResourceManager.GetString("AccountProblemAccessForbidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Problem Updating Account.
        /// </summary>
        internal static string AccountProblemAccessForbiddenTitle {
            get {
                return ResourceManager.GetString("AccountProblemAccessForbiddenTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please check that you&apos;ve provided your complete contact information..
        /// </summary>
        internal static string AccountProblemContactInformationInvalid {
            get {
                return ResourceManager.GetString("AccountProblemContactInformationInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The credit card information provided was incomplete..
        /// </summary>
        internal static string AccountProblemCreditCardInvalid {
            get {
                return ResourceManager.GetString("AccountProblemCreditCardInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Looks like we already have an account with that email address..
        /// </summary>
        internal static string AccountProblemEmailAlreadyExists {
            get {
                return ResourceManager.GetString("AccountProblemEmailAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Looks like there was a problem with the address provided, please confirm it is correct..
        /// </summary>
        internal static string AccountProblemShippingAddressInvalid {
            get {
                return ResourceManager.GetString("AccountProblemShippingAddressInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry! looks like there was an error, please try again..
        /// </summary>
        internal static string AccountProblemUnknownError {
            get {
                return ResourceManager.GetString("AccountProblemUnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to shipping address.
        /// </summary>
        internal static string AccountShippingAddress {
            get {
                return ResourceManager.GetString("AccountShippingAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        internal static string AddressLocal {
            get {
                return ResourceManager.GetString("AddressLocal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to postal code.
        /// </summary>
        internal static string AddressPostalCode {
            get {
                return ResourceManager.GetString("AddressPostalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to prefecture.
        /// </summary>
        internal static string AddressPrefecture {
            get {
                return ResourceManager.GetString("AddressPrefecture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to beerbox.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ABV.
        /// </summary>
        internal static string BeverageDetailsABV {
            get {
                return ResourceManager.GetString("BeverageDetailsABV", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string BeverageDetailsABVUnknown {
            get {
                return ResourceManager.GetString("BeverageDetailsABVUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to packaging.
        /// </summary>
        internal static string BeverageDetailsContainer {
            get {
                return ResourceManager.GetString("BeverageDetailsContainer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IBU.
        /// </summary>
        internal static string BeverageDetailsIBU {
            get {
                return ResourceManager.GetString("BeverageDetailsIBU", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string BeverageDetailsIBUUnknown {
            get {
                return ResourceManager.GetString("BeverageDetailsIBUUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to   •  .
        /// </summary>
        internal static string BeverageDetailsSeperator {
            get {
                return ResourceManager.GetString("BeverageDetailsSeperator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        internal static string BeverageDetailsSize {
            get {
                return ResourceManager.GetString("BeverageDetailsSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string BeverageDetailsTitle {
            get {
                return ResourceManager.GetString("BeverageDetailsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Beer.
        /// </summary>
        internal static string BeverageKindBeer {
            get {
                return ResourceManager.GetString("BeverageKindBeer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cider.
        /// </summary>
        internal static string BeverageKindCider {
            get {
                return ResourceManager.GetString("BeverageKindCider", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gin.
        /// </summary>
        internal static string BeverageKindGin {
            get {
                return ResourceManager.GetString("BeverageKindGin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mead.
        /// </summary>
        internal static string BeverageKindMead {
            get {
                return ResourceManager.GetString("BeverageKindMead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vodka.
        /// </summary>
        internal static string BeverageKindVodka {
            get {
                return ResourceManager.GetString("BeverageKindVodka", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Whisky.
        /// </summary>
        internal static string BeverageKindWhisky {
            get {
                return ResourceManager.GetString("BeverageKindWhisky", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wine.
        /// </summary>
        internal static string BeverageKindWine {
            get {
                return ResourceManager.GetString("BeverageKindWine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonAccept {
            get {
                return ResourceManager.GetString("ButtonAccept", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to change payment method.
        /// </summary>
        internal static string ChangePaymentMethodLink {
            get {
                return ResourceManager.GetString("ChangePaymentMethodLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to send message.
        /// </summary>
        internal static string ContactUsButtonSend {
            get {
                return ResourceManager.GetString("ContactUsButtonSend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent. Thank you for your feedback!.
        /// </summary>
        internal static string ContactUsThankYouMessage {
            get {
                return ResourceManager.GetString("ContactUsThankYouMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        internal static string ContactUsThankYouTitle {
            get {
                return ResourceManager.GetString("ContactUsThankYouTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to we&apos;d love to hear your thoughts.
        /// </summary>
        internal static string ContactUsMessage {
            get {
                return ResourceManager.GetString("ContactUsMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to subject.
        /// </summary>
        internal static string ContactUsSubject {
            get {
                return ResourceManager.GetString("ContactUsSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to © 2023 Beer Cats K.K..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        internal static string CreateAccountAgreeToTerms {
            get {
                return ResourceManager.GetString("CreateAccountAgreeToTerms", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string CreateAccountBirthdate {
            get {
                return ResourceManager.GetString("CreateAccountBirthdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must be at least 20 years old to use this service..
        /// </summary>
        internal static string CreateAccountBirthdateTip {
            get {
                return ResourceManager.GetString("CreateAccountBirthdateTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateAccountButtonCreate {
            get {
                return ResourceManager.GetString("CreateAccountButtonCreate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to billing address.
        /// </summary>
        internal static string CreditCardAddress {
            get {
                return ResourceManager.GetString("CreditCardAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Visa, Mastercard, American Express, JCB.
        /// </summary>
        internal static string CreditCardAllowedCards {
            get {
                return ResourceManager.GetString("CreditCardAllowedCards", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to card number.
        /// </summary>
        internal static string CreditCardCardNumber {
            get {
                return ResourceManager.GetString("CreditCardCardNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to expiration.
        /// </summary>
        internal static string CreditCardExpiration {
            get {
                return ResourceManager.GetString("CreditCardExpiration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string CreditCardExpirationMonth {
            get {
                return ResourceManager.GetString("CreditCardExpirationMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string CreditCardExpirationYear {
            get {
                return ResourceManager.GetString("CreditCardExpirationYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to name on card.
        /// </summary>
        internal static string CreditCardNameOnCard {
            get {
                return ResourceManager.GetString("CreditCardNameOnCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to credit card information is not stored on our servers.
        /// </summary>
        internal static string CreditCardNotStoredOnServer {
            get {
                return ResourceManager.GetString("CreditCardNotStoredOnServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to same as shipping address.
        /// </summary>
        internal static string CreditCardSameAsShipping {
            get {
                return ResourceManager.GetString("CreditCardSameAsShipping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CVV2/CVC2.
        /// </summary>
        internal static string CreditCardVerificationCode {
            get {
                return ResourceManager.GetString("CreditCardVerificationCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string EditAccountButtonSave {
            get {
                return ResourceManager.GetString("EditAccountButtonSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string EditAccountTitle {
            get {
                return ResourceManager.GetString("EditAccountTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to edit contact information.
        /// </summary>
        internal static string EditContactInfoLink {
            get {
                return ResourceManager.GetString("EditContactInfoLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Contact Information.
        /// </summary>
        internal static string EditContactInformationTitle {
            get {
                return ResourceManager.GetString("EditContactInformationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Payment Method.
        /// </summary>
        internal static string EditPaymentMethodTitle {
            get {
                return ResourceManager.GetString("EditPaymentMethodTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to edit shipping address.
        /// </summary>
        internal static string EditShippingAddressLink {
            get {
                return ResourceManager.GetString("EditShippingAddressLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Shipping Address.
        /// </summary>
        internal static string EditShippingAddressTitle {
            get {
                return ResourceManager.GetString("EditShippingAddressTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        internal static string HowItWorksContinue {
            get {
                return ResourceManager.GetString("HowItWorksContinue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to get started.
        /// </summary>
        internal static string HowItWorksGetStarted {
            get {
                return ResourceManager.GetString("HowItWorksGetStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to show me the beers!.
        /// </summary>
        internal static string HowItWorksShowMeTheBeverages {
            get {
                return ResourceManager.GetString("HowItWorksShowMeTheBeverages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How It Works.
        /// </summary>
        internal static string HowItWorksTitle {
            get {
                return ResourceManager.GetString("HowItWorksTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Oops! We don&apos;t seem to know about that account. Please check your email address..
        /// </summary>
        internal static string LoginAccountUnknown {
            get {
                return ResourceManager.GetString("LoginAccountUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string LoginButtonLogin {
            get {
                return ResourceManager.GetString("LoginButtonLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Oops! We&apos;ve run into a problem, please try again..
        /// </summary>
        internal static string LoginProblem {
            get {
                return ResourceManager.GetString("LoginProblem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to It seems you are no longer connected to the internet. Please reconnect to continue using beerbox..
        /// </summary>
        internal static string NetworkDisconnected {
            get {
                return ResourceManager.GetString("NetworkDisconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string NotificationAlertCancel {
            get {
                return ResourceManager.GetString("NotificationAlertCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to show beer.
        /// </summary>
        internal static string NotificationAlertShowOffer {
            get {
                return ResourceManager.GetString("NotificationAlertShowOffer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to almost gone.
        /// </summary>
        internal static string OfferAlmostGone {
            get {
                return ResourceManager.GetString("OfferAlmostGone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to add to beerbox.
        /// </summary>
        internal static string OfferConfirmAdd {
            get {
                return ResourceManager.GetString("OfferConfirmAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to update beerbox.
        /// </summary>
        internal static string OfferConfirmUpdate {
            get {
                return ResourceManager.GetString("OfferConfirmUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exclusive.
        /// </summary>
        internal static string OfferExclusive {
            get {
                return ResourceManager.GetString("OfferExclusive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This item is popular! We were only able to add __NUMBER__ to your beerbox..
        /// </summary>
        internal static string OfferInsufficientInventory {
            get {
                return ResourceManager.GetString("OfferInsufficientInventory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sold out!.
        /// </summary>
        internal static string OfferInsufficientInventoryTitle {
            get {
                return ResourceManager.GetString("OfferInsufficientInventoryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This item was popular! Looks like we&apos;ve run out of that beer..
        /// </summary>
        internal static string OfferNoInventory {
            get {
                return ResourceManager.GetString("OfferNoInventory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sold out!.
        /// </summary>
        internal static string OfferNoInventoryTitle {
            get {
                return ResourceManager.GetString("OfferNoInventoryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string OfferNone {
            get {
                return ResourceManager.GetString("OfferNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are currently not logged in. You may add items to your beerbox, but the reservations will not be finalized until you create an account and login..
        /// </summary>
        internal static string OfferNotLoggedInDescription {
            get {
                return ResourceManager.GetString("OfferNotLoggedInDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string OfferNotLoggedInLoginLater {
            get {
                return ResourceManager.GetString("OfferNotLoggedInLoginLater", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login / Create Account.
        /// </summary>
        internal static string OfferNotLoggedInLoginNow {
            get {
                return ResourceManager.GetString("OfferNotLoggedInLoginNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not Logged In.
        /// </summary>
        internal static string OfferNotLoggedInTitle {
            get {
                return ResourceManager.GetString("OfferNotLoggedInTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        internal static string OfferPrice {
            get {
                return ResourceManager.GetString("OfferPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to please pull down to refresh and try again.
        /// </summary>
        internal static string OfferProblemAdding {
            get {
                return ResourceManager.GetString("OfferProblemAdding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Oops! looks like there was an error.
        /// </summary>
        internal static string OfferProblemAddingTitle {
            get {
                return ResourceManager.GetString("OfferProblemAddingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to quantity.
        /// </summary>
        internal static string OfferQuantity {
            get {
                return ResourceManager.GetString("OfferQuantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string OfferQuantityDecrement {
            get {
                return ResourceManager.GetString("OfferQuantityDecrement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string OfferQuantityIncrement {
            get {
                return ResourceManager.GetString("OfferQuantityIncrement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This item has a limit of __MAX__ per order..
        /// </summary>
        internal static string OfferQuantityLimits {
            get {
                return ResourceManager.GetString("OfferQuantityLimits", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string OfferRare {
            get {
                return ResourceManager.GetString("OfferRare", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string OfferSale {
            get {
                return ResourceManager.GetString("OfferSale", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to __COUNT__ hidden.
        /// </summary>
        internal static string OffersHiddenCount {
            get {
                return ResourceManager.GetString("OffersHiddenCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to __COUNT__ total.
        /// </summary>
        internal static string OffersTotalCount {
            get {
                return ResourceManager.GetString("OffersTotalCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to __COUNT__ offers hidden by filters.
        /// </summary>
        internal static string OffersHiddenByFilters {
            get {
                return ResourceManager.GetString("OffersHiddenByFilters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hang tight while we prepare some new offers!.
        /// </summary>
        internal static string OffersNoCurrent1 {
            get {
                return ResourceManager.GetString("OffersNoCurrent1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We will notify you when we add new beers!.
        /// </summary>
        internal static string OffersNoCurrent2 {
            get {
                return ResourceManager.GetString("OffersNoCurrent2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to show all.
        /// </summary>
        internal static string OffersShowAll {
            get {
                return ResourceManager.GetString("OffersShowAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current Offers.
        /// </summary>
        internal static string OffersTitle {
            get {
                return ResourceManager.GetString("OffersTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        internal static string OfferTotal {
            get {
                return ResourceManager.GetString("OfferTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have an old version of beerbox. You will need to update to the latest version to use the app..
        /// </summary>
        internal static string OldVersionExplanation {
            get {
                return ResourceManager.GetString("OldVersionExplanation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to update now.
        /// </summary>
        internal static string OldVersionUpdateNow {
            get {
                return ResourceManager.GetString("OldVersionUpdateNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your current beerbox will close at end of __CLOSE_DATETIME__, so make sure you add any beers you want before it closes..
        /// </summary>
        internal static string OrderEndingSoonDescription {
            get {
                return ResourceManager.GetString("OrderEndingSoonDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to beerbox closing soon.
        /// </summary>
        internal static string OrderEndingSoonTitle {
            get {
                return ResourceManager.GetString("OrderEndingSoonTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My beerbox Items.
        /// </summary>
        internal static string OrderEntriesTitle {
            get {
                return ResourceManager.GetString("OrderEntriesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order History.
        /// </summary>
        internal static string OrderHistoryTitle {
            get {
                return ResourceManager.GetString("OrderHistoryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have no order history yet.
        /// </summary>
        internal static string OrderHistoryEmpty {
            get {
                return ResourceManager.GetString("OrderHistoryEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string OrderHistoryYear {
            get {
                return ResourceManager.GetString("OrderHistoryYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string OrderHistoryDate {
            get {
                return ResourceManager.GetString("OrderHistoryDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string OrderHistoryItems {
            get {
                return ResourceManager.GetString("OrderHistoryItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string OrderHistoryTotal {
            get {
                return ResourceManager.GetString("OrderHistoryTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your previous beerbox was closed and you now have a new empty beerbox..
        /// </summary>
        internal static string OrderRecentlyClosedDescription {
            get {
                return ResourceManager.GetString("OrderRecentlyClosedDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to new beerbox.
        /// </summary>
        internal static string OrderRecentlyClosedTitle {
            get {
                return ResourceManager.GetString("OrderRecentlyClosedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to COD.
        /// </summary>
        internal static string PaymentMethodCOD {
            get {
                return ResourceManager.GetString("PaymentMethodCOD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to credit card.
        /// </summary>
        internal static string PaymentMethodCreditCard {
            get {
                return ResourceManager.GetString("PaymentMethodCreditCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string PaymentMethodHeader {
            get {
                return ResourceManager.GetString("PaymentMethodHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is an issue with your payment method, &quot;__PROBLEM__&quot;.
        ///
        ///Please select a valid payment method or we may not be able to send your beerbox..
        /// </summary>
        internal static string PaymentMethodProblemBody {
            get {
                return ResourceManager.GetString("PaymentMethodProblemBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to set payment method now.
        /// </summary>
        internal static string PaymentMethodProblemNewCreditCard {
            get {
                return ResourceManager.GetString("PaymentMethodProblemNewCreditCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to set it later.
        /// </summary>
        internal static string PaymentMethodProblemNewCreditCardLater {
            get {
                return ResourceManager.GetString("PaymentMethodProblemNewCreditCardLater", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Issue With Payment Method.
        /// </summary>
        internal static string PaymentMethodProblemTitle {
            get {
                return ResourceManager.GetString("PaymentMethodProblemTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to card authorization failed.
        /// </summary>
        internal static string PaymentMethodStatusCardDeclined {
            get {
                return ResourceManager.GetString("PaymentMethodStatusCardDeclined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to your card has expired.
        /// </summary>
        internal static string PaymentMethodStatusExpiredCard {
            get {
                return ResourceManager.GetString("PaymentMethodStatusExpiredCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to incorrect CVC.
        /// </summary>
        internal static string PaymentMethodStatusIncorrectCvc {
            get {
                return ResourceManager.GetString("PaymentMethodStatusIncorrectCvc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to incorrect card number.
        /// </summary>
        internal static string PaymentMethodStatusIncorrectNumber {
            get {
                return ResourceManager.GetString("PaymentMethodStatusIncorrectNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to invalid postal code.
        /// </summary>
        internal static string PaymentMethodStatusIncorrectZip {
            get {
                return ResourceManager.GetString("PaymentMethodStatusIncorrectZip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to invalid CVC.
        /// </summary>
        internal static string PaymentMethodStatusInvalidCvc {
            get {
                return ResourceManager.GetString("PaymentMethodStatusInvalidCvc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to invalid expiration date.
        /// </summary>
        internal static string PaymentMethodStatusInvalidExpiryMonth {
            get {
                return ResourceManager.GetString("PaymentMethodStatusInvalidExpiryMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to invalid expiration date.
        /// </summary>
        internal static string PaymentMethodStatusInvalidExpiryYear {
            get {
                return ResourceManager.GetString("PaymentMethodStatusInvalidExpiryYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to invalid card number.
        /// </summary>
        internal static string PaymentMethodStatusInvalidNumber {
            get {
                return ResourceManager.GetString("PaymentMethodStatusInvalidNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to an unknown problem occurred.
        /// </summary>
        internal static string PaymentMethodStatusUnknown {
            get {
                return ResourceManager.GetString("PaymentMethodStatusUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Beverage Filter.
        /// </summary>
        internal static string SettingsBeverageFilter {
            get {
                return ResourceManager.GetString("SettingsBeverageFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filters apply to offers and notifications. Your beerbox and orders always show all kinds..
        /// </summary>
        internal static string SettingsBeverageFilterFooter {
            get {
                return ResourceManager.GetString("SettingsBeverageFilterFooter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string SettingsLanguageEnglish {
            get {
                return ResourceManager.GetString("SettingsLanguageEnglish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string SettingsLanguageJapanese {
            get {
                return ResourceManager.GetString("SettingsLanguageJapanese", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        internal static string SettingsLanguageSystem {
            get {
                return ResourceManager.GetString("SettingsLanguageSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string SettingsNotificationsDevice {
            get {
                return ResourceManager.GetString("SettingsNotificationsDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        internal static string SettingsNotificationsToken {
            get {
                return ResourceManager.GetString("SettingsNotificationsToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string SettingsEnvironment {
            get {
                return ResourceManager.GetString("SettingsEnvironment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service URL Override.
        /// </summary>
        internal static string SettingsServiceUrlOverride {
            get {
                return ResourceManager.GetString("SettingsServiceUrlOverride", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Leave empty for default.
        /// </summary>
        internal static string SettingsServiceUrlOverridePlaceholder {
            get {
                return ResourceManager.GetString("SettingsServiceUrlOverridePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Receive Test Notifications.
        /// </summary>
        internal static string SettingsReceiveTestNotifications {
            get {
                return ResourceManager.GetString("SettingsReceiveTestNotifications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Test Settings.
        /// </summary>
        internal static string SettingsShowTestSettings {
            get {
                return ResourceManager.GetString("SettingsShowTestSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Test Settings.
        /// </summary>
        internal static string SettingsTestSettings {
            get {
                return ResourceManager.GetString("SettingsTestSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to theme.
        /// </summary>
        internal static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to dark.
        /// </summary>
        internal static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to light.
        /// </summary>
        internal static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        internal static string SettingsThemeSystem {
            get {
                return ResourceManager.GetString("SettingsThemeSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Untappd Integration.
        /// </summary>
        internal static string SettingsUntappd {
            get {
                return ResourceManager.GetString("SettingsUntappd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Untappd is a free app that lets you track and rate beers you drink..
        /// </summary>
        internal static string SettingsUntappdAbout1 {
            get {
                return ResourceManager.GetString("SettingsUntappdAbout1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tap on the Untappd ratings on a beer page to open that beer in the Untappd app..
        /// </summary>
        internal static string SettingsUntappdAbout2 {
            get {
                return ResourceManager.GetString("SettingsUntappdAbout2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to show average rating.
        /// </summary>
        internal static string SettingsUntappdGlobalRating {
            get {
                return ResourceManager.GetString("SettingsUntappdGlobalRating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to login to Untappd.
        /// </summary>
        internal static string SettingsUntappdLogin {
            get {
                return ResourceManager.GetString("SettingsUntappdLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To turn on your Untappd ratings, you must first log in to beerbox..
        /// </summary>
        internal static string SettingsUntappdLoginTip {
            get {
                return ResourceManager.GetString("SettingsUntappdLoginTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to show your rating.
        /// </summary>
        internal static string SettingsUntappdPersonalRating {
            get {
                return ResourceManager.GetString("SettingsUntappdPersonalRating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to your order.
        /// </summary>
        internal static string SummaryCosts {
            get {
                return ResourceManager.GetString("SummaryCosts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to beers.
        /// </summary>
        internal static string SummaryCostsBeverages {
            get {
                return ResourceManager.GetString("SummaryCostsBeverages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to shipping.
        /// </summary>
        internal static string SummaryCostsShipping {
            get {
                return ResourceManager.GetString("SummaryCostsShipping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cool shipping is free for orders above ¥{0:#,0}..
        /// </summary>
        internal static string SummaryCostsShippingTip {
            get {
                return ResourceManager.GetString("SummaryCostsShippingTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        internal static string SummaryCostsTotal {
            get {
                return ResourceManager.GetString("SummaryCostsTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to keep adding beers until.
        /// </summary>
        internal static string SummaryEndDate {
            get {
                return ResourceManager.GetString("SummaryEndDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to check my beerbox.
        /// </summary>
        internal static string SummaryLinkShowDetails {
            get {
                return ResourceManager.GetString("SummaryLinkShowDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login / Create Account.
        /// </summary>
        internal static string SummaryLoginButton {
            get {
                return ResourceManager.GetString("SummaryLoginButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are currently logged out. We will keep track of the beers you select in this beerbox, but they will not be reserved and will not ship until you log in..
        /// </summary>
        internal static string SummaryNotLoggedIn {
            get {
                return ResourceManager.GetString("SummaryNotLoggedIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to my beerbox.
        /// </summary>
        internal static string SummarySelectedBeverages {
            get {
                return ResourceManager.GetString("SummarySelectedBeverages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to planned shipping date.
        /// </summary>
        internal static string SummaryShipDate {
            get {
                return ResourceManager.GetString("SummaryShipDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My beerbox.
        /// </summary>
        internal static string SummaryTitle {
            get {
                return ResourceManager.GetString("SummaryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        internal static string SummaryTotalBeverages {
            get {
                return ResourceManager.GetString("SummaryTotalBeverages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to unique.
        /// </summary>
        internal static string SummaryUniqueBeverages {
            get {
                return ResourceManager.GetString("SummaryUniqueBeverages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (tax incl.).
        /// </summary>
        internal static string TaxIncluded {
            get {
                return ResourceManager.GetString("TaxIncluded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company Name: no Beer Cats KK
        ///Established: October 2013
        ///TEL: 03-5904-8949
        ///Address: 6-10-14 A602 Otsuka, Bunkyo-ku, Tokyo, 112-0012
        ///Managing Director: Todd Michael Stevens
        ///
        ///Orders:
        ///Within this application, by adding products to your &apos;beer box&apos; you are making an agreement to complete purchase of those items on the cutoff date.
        ///
        ///Upon the monthly cutoff date, your box will be closed and all received orders will be finalized. We will ship your box the following day for next day delivery. However, Hokkaido, Aomor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TermsAndConditionsBody {
            get {
                return ResourceManager.GetString("TermsAndConditionsBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string UntappdLoginStatusDone {
            get {
                return ResourceManager.GetString("UntappdLoginStatusDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to establishing connection.
        /// </summary>
        internal static string UntappdLoginStatusEstablishingConnection {
            get {
                return ResourceManager.GetString("UntappdLoginStatusEstablishingConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string UntappdLoginStatusLogin {
            get {
                return ResourceManager.GetString("UntappdLoginStatusLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to verification.
        /// </summary>
        internal static string UntappdLoginStatusVerifications {
            get {
                return ResourceManager.GetString("UntappdLoginStatusVerifications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to login to Untappd.
        /// </summary>
        internal static string UntappdLoginTitle {
            get {
                return ResourceManager.GetString("UntappdLoginTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to you.
        /// </summary>
        internal static string UntappdPersonalRating {
            get {
                return ResourceManager.GetString("UntappdPersonalRating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to community.
        /// </summary>
        internal static string UntappdRating {
            get {
                return ResourceManager.GetString("UntappdRating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A verification email has been sent to __EMAIL__. Please click on the link in the email to activate your account..
        /// </summary>
        internal static string WaitVerificationExplanation1 {
            get {
                return ResourceManager.GetString("WaitVerificationExplanation1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Once you click the link, your account will be activated..
        /// </summary>
        internal static string WaitVerificationExplanation2 {
            get {
                return ResourceManager.GetString("WaitVerificationExplanation2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve carried the items you ordered into your new account&apos;s beerbox..
        /// </summary>
        internal static string WaitVerificationMergeBoxDescription {
            get {
                return ResourceManager.GetString("WaitVerificationMergeBoxDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Merged beerbox.
        /// </summary>
        internal static string WaitVerificationMergeBoxTitle {
            get {
                return ResourceManager.GetString("WaitVerificationMergeBoxTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email Verification.
        /// </summary>
        internal static string WaitVerificationTitle {
            get {
                return ResourceManager.GetString("WaitVerificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ¥.
        /// </summary>
        internal static string Yen {
            get {
                return ResourceManager.GetString("Yen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ¥{0:#,0}.
        /// </summary>
        internal static string YenBeforeNumber {
            get {
                return ResourceManager.GetString("YenBeforeNumber", resourceCulture);
            }
        }
    }
}
